# Generated by Django 5.1.6 on 2025-03-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_market_or_limit_alter_order_order_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='market_or_limit',
            field=models.CharField(blank=True, choices=[('LIMIT', 'LIMIT'), ('MARKET', 'MARKET')], max_length=6, null=True),
        ),
    ]
