# Generated by Django 5.1.6 on 2025-03-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_order_type_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
