# Generated by Django 5.1.6 on 2025-03-06 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_expiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='expiry',
        ),
    ]
