# Generated by Django 5.1.6 on 2025-03-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_order_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
